//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;



 
public partial class Tables
{
    public Conf.ItemInfos ItemInfos {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        ItemInfos = new Conf.ItemInfos(loader("Conf.ItemInfo")); 
        tables.Add("Conf.ItemInfos", ItemInfos);

        PostInit();
        ItemInfos.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        ItemInfos.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

