
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;


public partial class Tables
{
    public static List<string> tables { get; private set; } = new()
    {
        "Conf.ItemInfo",
    };

    public Conf.ItemInfos ItemInfos {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        ItemInfos = new Conf.ItemInfos(loader("Conf.ItemInfo"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        ItemInfos.ResolveRef(this);
    }
}


