
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Conf
{
public sealed partial class AttributeInfo : Luban.BeanBase
{
    public AttributeInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        HP = _buf.ReadInt();
        MaxHP = _buf.ReadInt();
        MoveSpeed = _buf.ReadInt();
        Attack = _buf.ReadInt();
    }

    public static AttributeInfo DeserializeAttributeInfo(ByteBuf _buf)
    {
        return new Conf.AttributeInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 当前生命值
    /// </summary>
    public readonly int HP;
    /// <summary>
    /// 最大生命值
    /// </summary>
    public readonly int MaxHP;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly int MoveSpeed;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
   
    public const int __ID__ = -1794876384;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "HP:" + HP + ","
        + "MaxHP:" + MaxHP + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "Attack:" + Attack + ","
        + "}";
    }
}

}

