
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Conf
{
public sealed partial class ModelInfo : Luban.BeanBase
{
    public ModelInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Res = _buf.ReadString();
        Animation = _buf.ReadString();
    }

    public static ModelInfo DeserializeModelInfo(ByteBuf _buf)
    {
        return new Conf.ModelInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 模型路径
    /// </summary>
    public readonly string Res;
    /// <summary>
    /// 动画路径
    /// </summary>
    public readonly string Animation;
   
    public const int __ID__ = 236415277;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Res:" + Res + ","
        + "Animation:" + Animation + ","
        + "}";
    }
}

}

