
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Conf
{
public partial class BuffInfos
{
    private readonly System.Collections.Generic.Dictionary<int, Conf.BuffInfo> _dataMap;
    private readonly System.Collections.Generic.List<Conf.BuffInfo> _dataList;
    
    public BuffInfos(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Conf.BuffInfo>();
        _dataList = new System.Collections.Generic.List<Conf.BuffInfo>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Conf.BuffInfo _v;
            _v = Conf.BuffInfo.DeserializeBuffInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Conf.BuffInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Conf.BuffInfo> DataList => _dataList;

    public bool TryGetValue(int key, out Conf.BuffInfo value) => _dataMap.TryGetValue(key, out value);
    public Conf.BuffInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Conf.BuffInfo Get(int key) => _dataMap[key];
    public Conf.BuffInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

