
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Conf
{
public sealed partial class BuffInfo : Luban.BeanBase
{
    public BuffInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);EnchantMains = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); EnchantMains.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);EnchantScales = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); EnchantScales.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Pipelines = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Pipelines.Add(_e0);}}
    }

    public static BuffInfo DeserializeBuffInfo(ByteBuf _buf)
    {
        return new Conf.BuffInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Buff 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 属性赋予
    /// </summary>
    public readonly System.Collections.Generic.List<int> EnchantMains;
    /// <summary>
    /// 属性赋予 (千分比)
    /// </summary>
    public readonly System.Collections.Generic.List<int> EnchantScales;
    /// <summary>
    /// 管线
    /// </summary>
    public readonly System.Collections.Generic.List<int> Pipelines;
   
    public const int __ID__ = 1597663019;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "EnchantMains:" + Luban.StringUtil.CollectionToString(EnchantMains) + ","
        + "EnchantScales:" + Luban.StringUtil.CollectionToString(EnchantScales) + ","
        + "Pipelines:" + Luban.StringUtil.CollectionToString(Pipelines) + ","
        + "}";
    }
}

}

