
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace Conf
{
public sealed partial class BuffInfo : Luban.BeanBase
{
    public BuffInfo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("Id").GetInt32();
        Name = _buf.GetProperty("Name").GetString();
        { var __json0 = _buf.GetProperty("EnchantMains"); EnchantMains = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  EnchantMains.Add(__v0); }   }
        { var __json0 = _buf.GetProperty("EnchantScales"); EnchantScales = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  EnchantScales.Add(__v0); }   }
        { var __json0 = _buf.GetProperty("Pipelines"); Pipelines = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  Pipelines.Add(__v0); }   }
    }

    public static BuffInfo DeserializeBuffInfo(JsonElement _buf)
    {
        return new Conf.BuffInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Buff 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 属性赋予
    /// </summary>
    public readonly System.Collections.Generic.List<int> EnchantMains;
    /// <summary>
    /// 属性赋予 (千分比)
    /// </summary>
    public readonly System.Collections.Generic.List<int> EnchantScales;
    /// <summary>
    /// 管线
    /// </summary>
    public readonly System.Collections.Generic.List<int> Pipelines;
   
    public const int __ID__ = 1597663019;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "EnchantMains:" + Luban.StringUtil.CollectionToString(EnchantMains) + ","
        + "EnchantScales:" + Luban.StringUtil.CollectionToString(EnchantScales) + ","
        + "Pipelines:" + Luban.StringUtil.CollectionToString(Pipelines) + ","
        + "}";
    }
}

}

