
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Conf
{
public sealed partial class ColliderInfo : Luban.BeanBase
{
    public ColliderInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Offset = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Offset.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Shape = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Shape.Add(_e0);}}
    }

    public static ColliderInfo DeserializeColliderInfo(ByteBuf _buf)
    {
        return new Conf.ColliderInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 偏移
    /// </summary>
    public readonly System.Collections.Generic.List<int> Offset;
    /// <summary>
    /// 几何体数据
    /// </summary>
    public readonly System.Collections.Generic.List<int> Shape;
   
    public const int __ID__ = -2022366900;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Offset:" + Luban.StringUtil.CollectionToString(Offset) + ","
        + "Shape:" + Luban.StringUtil.CollectionToString(Shape) + ","
        + "}";
    }
}

}

