
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace Conf
{
public sealed partial class ColliderInfo : Luban.BeanBase
{
    public ColliderInfo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("Id").GetInt32();
        Type = _buf.GetProperty("Type").GetInt32();
        { var __json0 = _buf.GetProperty("Offset"); Offset = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  Offset.Add(__v0); }   }
        { var __json0 = _buf.GetProperty("Shape"); Shape = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  Shape.Add(__v0); }   }
    }

    public static ColliderInfo DeserializeColliderInfo(JsonElement _buf)
    {
        return new Conf.ColliderInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 偏移
    /// </summary>
    public readonly System.Collections.Generic.List<int> Offset;
    /// <summary>
    /// 几何体数据
    /// </summary>
    public readonly System.Collections.Generic.List<int> Shape;
   
    public const int __ID__ = -2022366900;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Offset:" + Luban.StringUtil.CollectionToString(Offset) + ","
        + "Shape:" + Luban.StringUtil.CollectionToString(Shape) + ","
        + "}";
    }
}

}

