
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace Conf
{
public sealed partial class EffectInfo : Luban.BeanBase
{
    public EffectInfo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("Id").GetInt32();
        Name = _buf.GetProperty("Name").GetString();
        Res = _buf.GetProperty("Res").GetString();
        Duration = _buf.GetProperty("Duration").GetInt32();
    }

    public static EffectInfo DeserializeEffectInfo(JsonElement _buf)
    {
        return new Conf.EffectInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 特效名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 资源路径
    /// </summary>
    public readonly string Res;
    /// <summary>
    /// 持续时间(毫秒)
    /// </summary>
    public readonly int Duration;
   
    public const int __ID__ = -1630124311;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Res:" + Res + ","
        + "Duration:" + Duration + ","
        + "}";
    }
}

}

