
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Conf
{
public sealed partial class HeroInfo : Luban.BeanBase
{
    public HeroInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Attribute = _buf.ReadInt();
        Name = _buf.ReadString();
        Model = _buf.ReadInt();
        Collider = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Skills = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Skills.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BornPipelines = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); BornPipelines.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);DeathPipelines = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); DeathPipelines.Add(_e0);}}
    }

    public static HeroInfo DeserializeHeroInfo(ByteBuf _buf)
    {
        return new Conf.HeroInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 属性
    /// </summary>
    public readonly int Attribute;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 模型
    /// </summary>
    public readonly int Model;
    /// <summary>
    /// 碰撞盒 ID
    /// </summary>
    public readonly int Collider;
    /// <summary>
    /// 技能列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> Skills;
    /// <summary>
    /// 出生管线
    /// </summary>
    public readonly System.Collections.Generic.List<int> BornPipelines;
    /// <summary>
    /// 死亡管线
    /// </summary>
    public readonly System.Collections.Generic.List<int> DeathPipelines;
   
    public const int __ID__ = -1793672366;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Attribute:" + Attribute + ","
        + "Name:" + Name + ","
        + "Model:" + Model + ","
        + "Collider:" + Collider + ","
        + "Skills:" + Luban.StringUtil.CollectionToString(Skills) + ","
        + "BornPipelines:" + Luban.StringUtil.CollectionToString(BornPipelines) + ","
        + "DeathPipelines:" + Luban.StringUtil.CollectionToString(DeathPipelines) + ","
        + "}";
    }
}

}

