
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace Conf
{
public sealed partial class ModelInfo : Luban.BeanBase
{
    public ModelInfo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("Id").GetInt32();
        Res = _buf.GetProperty("Res").GetString();
        Animation = _buf.GetProperty("Animation").GetString();
        Type = _buf.GetProperty("Type").GetString();
        Mesh = _buf.GetProperty("Mesh").GetString();
        { var __json0 = _buf.GetProperty("Size"); Size = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  Size.Add(__v0); }   }
        { var __json0 = _buf.GetProperty("Color"); Color = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  Color.Add(__v0); }   }
    }

    public static ModelInfo DeserializeModelInfo(JsonElement _buf)
    {
        return new Conf.ModelInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 模型路径
    /// </summary>
    public readonly string Res;
    /// <summary>
    /// 动画路径
    /// </summary>
    public readonly string Animation;
    /// <summary>
    /// 类型(glb/primitive)
    /// </summary>
    public readonly string Type;
    /// <summary>
    /// 基元形状(box/cylinder/sphere)
    /// </summary>
    public readonly string Mesh;
    /// <summary>
    /// 尺寸(mm)
    /// </summary>
    public readonly System.Collections.Generic.List<int> Size;
    /// <summary>
    /// 颜色(RGBA 0-255)
    /// </summary>
    public readonly System.Collections.Generic.List<int> Color;
   
    public const int __ID__ = 236415277;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Res:" + Res + ","
        + "Animation:" + Animation + ","
        + "Type:" + Type + ","
        + "Mesh:" + Mesh + ","
        + "Size:" + Luban.StringUtil.CollectionToString(Size) + ","
        + "Color:" + Luban.StringUtil.CollectionToString(Color) + ","
        + "}";
    }
}

}

