
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Conf
{
public partial class SkillInfos
{
    private readonly System.Collections.Generic.Dictionary<int, Conf.SkillInfo> _dataMap;
    private readonly System.Collections.Generic.List<Conf.SkillInfo> _dataList;
    
    public SkillInfos(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Conf.SkillInfo>();
        _dataList = new System.Collections.Generic.List<Conf.SkillInfo>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Conf.SkillInfo _v;
            _v = Conf.SkillInfo.DeserializeSkillInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Conf.SkillInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Conf.SkillInfo> DataList => _dataList;

    public bool TryGetValue(int key, out Conf.SkillInfo value) => _dataMap.TryGetValue(key, out value);
    public Conf.SkillInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Conf.SkillInfo Get(int key) => _dataMap[key];
    public Conf.SkillInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

