
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace Conf
{
public sealed partial class SoundInfo : Luban.BeanBase
{
    public SoundInfo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("Id").GetInt32();
        Res = _buf.GetProperty("Res").GetString();
        Category = _buf.GetProperty("Category").GetByte();
        DefaultVolume = _buf.GetProperty("DefaultVolume").GetSingle();
    }

    public static SoundInfo DeserializeSoundInfo(JsonElement _buf)
    {
        return new Conf.SoundInfo(_buf);
    }

    /// <summary>
    /// 音效 ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源文件名
    /// </summary>
    public readonly string Res;
    /// <summary>
    /// 分类：0=SFX, 1=BGM, 2=UI
    /// </summary>
    public readonly byte Category;
    /// <summary>
    /// 默认音量
    /// </summary>
    public readonly float DefaultVolume;
   
    public const int __ID__ = -2048000001;
    public override int GetTypeId() => __ID__;

    public void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Res:" + Res + ","
        + "Category:" + Category + ","
        + "DefaultVolume:" + DefaultVolume + ","
        + "}";
    }
}

}
