using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Goblin.SourceGenerators;

/// <summary>
/// Goblin Source Generator 入口
/// 扫描 partial class + IGBL → 产出 .g.cs（T1.1 空管线验证）
/// </summary>
[Generator]
public class GoblinSourceGenerator : IIncrementalGenerator
{
    private const string IGBL_FULLNAME = "Goblin.Common.IGBL";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 筛选 partial class 声明
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsPartialClass(node),
                transform: static (ctx, _) => GetTargetSymbol(ctx))
            .Where(static symbol => null != symbol);

        // 为每个符合条件的类产出空 .g.cs
        context.RegisterSourceOutput(classDeclarations,
            static (spc, symbol) => EmitEmptyPartial(spc, symbol));
    }

    /// <summary>
    /// 语法层过滤：只保留 partial class
    /// </summary>
    private static bool IsPartialClass(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax classDecl) return false;

        foreach (var modifier in classDecl.Modifiers)
        {
            if (modifier.IsKind(SyntaxKind.PartialKeyword)) return true;
        }

        return false;
    }

    /// <summary>
    /// 语义层过滤：检查是否实现 IGBL 接口（含继承链）
    /// </summary>
    private static INamedTypeSymbol? GetTargetSymbol(GeneratorSyntaxContext ctx)
    {
        if (ctx.Node is not ClassDeclarationSyntax classDecl) return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl);
        if (null == symbol) return null;

        // 检查直接实现或通过基类继承 IGBL
        foreach (var iface in symbol.AllInterfaces)
        {
            if (IGBL_FULLNAME == GetFullMetadataName(iface)) return symbol;
        }

        return null;
    }

    /// <summary>
    /// 产出空 partial 类（T1.1 管线验证）
    /// </summary>
    private static void EmitEmptyPartial(SourceProductionContext context, INamedTypeSymbol symbol)
    {
        var namespaceName = symbol.ContainingNamespace.ToDisplayString();
        var className = symbol.Name;

        var source = $@"// <auto-generated/>
namespace {namespaceName};

partial class {className}
{{
}}
";

        var hintName = $"{namespaceName}.{className}.g.cs";
        context.AddSource(hintName, source);
    }

    /// <summary>
    /// 获取类型的完整元数据名（含命名空间，用 . 分隔）
    /// </summary>
    private static string GetFullMetadataName(INamedTypeSymbol symbol)
    {
        var parts = new System.Collections.Generic.List<string>();
        var current = (ISymbol)symbol;

        while (null != current && current is not INamespaceSymbol { IsGlobalNamespace: true })
        {
            parts.Add(current.Name);
            current = current.ContainingSymbol;
        }

        parts.Reverse();
        return string.Join(".", parts);
    }
}
