//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;



 
public partial class Tables
{
    public Conf.Gameplay.UpgradeInfos UpgradeInfos {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        UpgradeInfos = new Conf.Gameplay.UpgradeInfos(loader("Conf.Gameplay.UpgradeInfos")); 
        tables.Add("Conf.Gameplay.UpgradeInfos", UpgradeInfos);

        PostInit();
        UpgradeInfos.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        UpgradeInfos.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

