
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;


public partial class Tables
{
    public static List<string> tables { get; private set; } = new()
    {
        "Conf.ItemInfo",
        "Conf.AttributeInfo",
        "Conf.ModelInfo",
        "Conf.HeroInfo",
        "Conf.ColliderInfo",
        "Conf.SkillInfo",
        "Conf.SkillTriggerInfo",
    };

    public Conf.ItemInfos ItemInfos {get; }
    public Conf.AttributeInfos AttributeInfos {get; }
    public Conf.ModelInfos ModelInfos {get; }
    public Conf.HeroInfos HeroInfos {get; }
    public Conf.ColliderInfos ColliderInfos {get; }
    public Conf.SkillInfos SkillInfos {get; }
    public Conf.SkillTriggerInfos SkillTriggerInfos {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        ItemInfos = new Conf.ItemInfos(loader("Conf.ItemInfo"));
        AttributeInfos = new Conf.AttributeInfos(loader("Conf.AttributeInfo"));
        ModelInfos = new Conf.ModelInfos(loader("Conf.ModelInfo"));
        HeroInfos = new Conf.HeroInfos(loader("Conf.HeroInfo"));
        ColliderInfos = new Conf.ColliderInfos(loader("Conf.ColliderInfo"));
        SkillInfos = new Conf.SkillInfos(loader("Conf.SkillInfo"));
        SkillTriggerInfos = new Conf.SkillTriggerInfos(loader("Conf.SkillTriggerInfo"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        ItemInfos.ResolveRef(this);
        AttributeInfos.ResolveRef(this);
        ModelInfos.ResolveRef(this);
        HeroInfos.ResolveRef(this);
        ColliderInfos.ResolveRef(this);
        SkillInfos.ResolveRef(this);
        SkillTriggerInfos.ResolveRef(this);
    }
}


