
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace Conf
{
public sealed partial class AttributeInfo : Luban.BeanBase
{
    public AttributeInfo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("Id").GetInt32();
        HP = _buf.GetProperty("HP").GetInt32();
        MaxHP = _buf.GetProperty("MaxHP").GetInt32();
        MoveSpeed = _buf.GetProperty("MoveSpeed").GetInt32();
        Attack = _buf.GetProperty("Attack").GetInt32();
        Armor = _buf.TryGetProperty("Armor", out var _armor) ? _armor.GetInt32() : 0;
        MagicResist = _buf.TryGetProperty("MagicResist", out var _magicresist) ? _magicresist.GetInt32() : 0;
        CritRate = _buf.TryGetProperty("CritRate", out var _critrate) ? _critrate.GetInt32() : 0;
        DodgeRate = _buf.TryGetProperty("DodgeRate", out var _dodgerate) ? _dodgerate.GetInt32() : 0;
    }

    public static AttributeInfo DeserializeAttributeInfo(JsonElement _buf)
    {
        return new Conf.AttributeInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 当前生命值
    /// </summary>
    public readonly int HP;
    /// <summary>
    /// 最大生命值
    /// </summary>
    public readonly int MaxHP;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly int MoveSpeed;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 护甲
    /// </summary>
    public readonly int Armor;
    /// <summary>
    /// 魔法抗性
    /// </summary>
    public readonly int MagicResist;
    /// <summary>
    /// 暴击率（千分比）
    /// </summary>
    public readonly int CritRate;
    /// <summary>
    /// 闪避率（千分比）
    /// </summary>
    public readonly int DodgeRate;
   
    public const int __ID__ = -1794876384;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "HP:" + HP + ","
        + "MaxHP:" + MaxHP + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "Attack:" + Attack + ","
        + "Armor:" + Armor + ","
        + "MagicResist:" + MagicResist + ","
        + "CritRate:" + CritRate + ","
        + "DodgeRate:" + DodgeRate + ","
        + "}";
    }
}

}

