
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Conf
{
public partial class AttributeInfos
{
    private readonly System.Collections.Generic.Dictionary<int, Conf.AttributeInfo> _dataMap;
    private readonly System.Collections.Generic.List<Conf.AttributeInfo> _dataList;
    
    public AttributeInfos(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Conf.AttributeInfo>();
        _dataList = new System.Collections.Generic.List<Conf.AttributeInfo>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Conf.AttributeInfo _v;
            _v = Conf.AttributeInfo.DeserializeAttributeInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Conf.AttributeInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Conf.AttributeInfo> DataList => _dataList;

    public Conf.AttributeInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Conf.AttributeInfo Get(int key) => _dataMap[key];
    public Conf.AttributeInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

