
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace Conf
{
public sealed partial class EnemyInfo : Luban.BeanBase
{
    public EnemyInfo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("Id").GetInt32();
        Attribute = _buf.GetProperty("Attribute").GetInt32();
        Name = _buf.GetProperty("Name").GetString();
        Model = _buf.GetProperty("Model").GetInt32();
        Collider = _buf.GetProperty("Collider").GetInt32();
        { var __json0 = _buf.GetProperty("BornPipelines"); BornPipelines = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  BornPipelines.Add(__v0); }   }
        { var __json0 = _buf.GetProperty("DeathPipelines"); DeathPipelines = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  DeathPipelines.Add(__v0); }   }
        AttackRange = _buf.GetProperty("AttackRange").GetInt32();
    }

    public static EnemyInfo DeserializeEnemyInfo(JsonElement _buf)
    {
        return new Conf.EnemyInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 属性
    /// </summary>
    public readonly int Attribute;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 模型
    /// </summary>
    public readonly int Model;
    /// <summary>
    /// 碰撞盒 ID
    /// </summary>
    public readonly int Collider;
    /// <summary>
    /// 出生管线
    /// </summary>
    public readonly System.Collections.Generic.List<int> BornPipelines;
    /// <summary>
    /// 死亡管线
    /// </summary>
    public readonly System.Collections.Generic.List<int> DeathPipelines;
    /// <summary>
    /// 攻击距离(毫米)
    /// </summary>
    public readonly int AttackRange;
   
    public const int __ID__ = 1196881420;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Attribute:" + Attribute + ","
        + "Name:" + Name + ","
        + "Model:" + Model + ","
        + "Collider:" + Collider + ","
        + "BornPipelines:" + Luban.StringUtil.CollectionToString(BornPipelines) + ","
        + "DeathPipelines:" + Luban.StringUtil.CollectionToString(DeathPipelines) + ","
        + "AttackRange:" + AttackRange + ","
        + "}";
    }
}

}

