
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Conf
{
public partial class HeroInfos
{
    private readonly System.Collections.Generic.Dictionary<int, Conf.HeroInfo> _dataMap;
    private readonly System.Collections.Generic.List<Conf.HeroInfo> _dataList;
    
    public HeroInfos(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Conf.HeroInfo>();
        _dataList = new System.Collections.Generic.List<Conf.HeroInfo>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Conf.HeroInfo _v;
            _v = Conf.HeroInfo.DeserializeHeroInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Conf.HeroInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Conf.HeroInfo> DataList => _dataList;

    public bool TryGetValue(int key, out Conf.HeroInfo value) => _dataMap.TryGetValue(key, out value);
    public Conf.HeroInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Conf.HeroInfo Get(int key) => _dataMap[key];
    public Conf.HeroInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

