
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace Conf
{
public partial class ItemInfos
{
    private readonly System.Collections.Generic.Dictionary<int, Conf.ItemInfo> _dataMap;
    private readonly System.Collections.Generic.List<Conf.ItemInfo> _dataList;
    
    public ItemInfos(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Conf.ItemInfo>();
        _dataList = new System.Collections.Generic.List<Conf.ItemInfo>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            Conf.ItemInfo _v;
            _v = Conf.ItemInfo.DeserializeItemInfo(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Conf.ItemInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Conf.ItemInfo> DataList => _dataList;

    public bool TryGetValue(int key, out Conf.ItemInfo value) => _dataMap.TryGetValue(key, out value);
    public Conf.ItemInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Conf.ItemInfo Get(int key) => _dataMap[key];
    public Conf.ItemInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

