
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Conf
{
public partial class PipelineInfos
{
    private readonly System.Collections.Generic.Dictionary<int, Conf.PipelineInfo> _dataMap;
    private readonly System.Collections.Generic.List<Conf.PipelineInfo> _dataList;
    
    public PipelineInfos(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Conf.PipelineInfo>();
        _dataList = new System.Collections.Generic.List<Conf.PipelineInfo>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Conf.PipelineInfo _v;
            _v = Conf.PipelineInfo.DeserializePipelineInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Conf.PipelineInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Conf.PipelineInfo> DataList => _dataList;

    public bool TryGetValue(int key, out Conf.PipelineInfo value) => _dataMap.TryGetValue(key, out value);
    public Conf.PipelineInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Conf.PipelineInfo Get(int key) => _dataMap[key];
    public Conf.PipelineInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

