
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace Conf
{
public partial class SkillInfos
{
    private readonly System.Collections.Generic.Dictionary<int, Conf.SkillInfo> _dataMap;
    private readonly System.Collections.Generic.List<Conf.SkillInfo> _dataList;
    
    public SkillInfos(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Conf.SkillInfo>();
        _dataList = new System.Collections.Generic.List<Conf.SkillInfo>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            Conf.SkillInfo _v;
            _v = Conf.SkillInfo.DeserializeSkillInfo(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Conf.SkillInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Conf.SkillInfo> DataList => _dataList;

    public Conf.SkillInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Conf.SkillInfo Get(int key) => _dataMap[key];
    public Conf.SkillInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

