
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Conf
{
public partial class SkillBindingInfos
{
    private readonly System.Collections.Generic.Dictionary<int, Conf.SkillBindingInfo> _dataMap;
    private readonly System.Collections.Generic.List<Conf.SkillBindingInfo> _dataList;
    
    public SkillBindingInfos(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Conf.SkillBindingInfo>();
        _dataList = new System.Collections.Generic.List<Conf.SkillBindingInfo>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Conf.SkillBindingInfo _v;
            _v = Conf.SkillBindingInfo.DeserializeSkillBindingInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Conf.SkillBindingInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Conf.SkillBindingInfo> DataList => _dataList;

    public Conf.SkillBindingInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Conf.SkillBindingInfo Get(int key) => _dataMap[key];
    public Conf.SkillBindingInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

