
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Conf
{
public sealed partial class SkillInfo : Luban.BeanBase
{
    public SkillInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Strength = _buf.ReadInt();
        Cooldown = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Pipelines = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Pipelines.Add(_e0);}}
    }

    public static SkillInfo DeserializeSkillInfo(ByteBuf _buf)
    {
        return new Conf.SkillInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 伤害强度
    /// </summary>
    public readonly int Strength;
    /// <summary>
    /// 冷却时间
    /// </summary>
    public readonly int Cooldown;
    /// <summary>
    /// 管线
    /// </summary>
    public readonly System.Collections.Generic.List<int> Pipelines;
   
    public const int __ID__ = -56728491;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Strength:" + Strength + ","
        + "Cooldown:" + Cooldown + ","
        + "Pipelines:" + Luban.StringUtil.CollectionToString(Pipelines) + ","
        + "}";
    }
}

}

