
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace Conf
{
public sealed partial class SkillInfo : Luban.BeanBase
{
    public SkillInfo(JsonElement _buf) 
    {
        Id = _buf.GetProperty("Id").GetInt32();
        Name = _buf.GetProperty("Name").GetString();
        Strength = _buf.GetProperty("Strength").GetInt32();
        Cooldown = _buf.GetProperty("Cooldown").GetInt32();
        { var __json0 = _buf.GetProperty("Pipelines"); Pipelines = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  Pipelines.Add(__v0); }   }
    }

    public static SkillInfo DeserializeSkillInfo(JsonElement _buf)
    {
        return new Conf.SkillInfo(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 伤害强度
    /// </summary>
    public readonly int Strength;
    /// <summary>
    /// 冷却时间
    /// </summary>
    public readonly int Cooldown;
    /// <summary>
    /// 管线
    /// </summary>
    public readonly System.Collections.Generic.List<int> Pipelines;
   
    public const int __ID__ = -56728491;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Strength:" + Strength + ","
        + "Cooldown:" + Cooldown + ","
        + "Pipelines:" + Luban.StringUtil.CollectionToString(Pipelines) + ","
        + "}";
    }
}

}

