
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


namespace Conf
{
public partial class SoundInfos
{
    private readonly System.Collections.Generic.Dictionary<int, Conf.SoundInfo> _dataMap;
    private readonly System.Collections.Generic.List<Conf.SoundInfo> _dataList;
    
    public SoundInfos(JsonElement _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Conf.SoundInfo>();
        _dataList = new System.Collections.Generic.List<Conf.SoundInfo>();
        
        foreach(JsonElement _ele in _buf.EnumerateArray())
        {
            Conf.SoundInfo _v;
            _v = Conf.SoundInfo.DeserializeSoundInfo(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Conf.SoundInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<Conf.SoundInfo> DataList => _dataList;

    public bool TryGetValue(int key, out Conf.SoundInfo value) => _dataMap.TryGetValue(key, out value);
    public Conf.SoundInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Conf.SoundInfo Get(int key) => _dataMap[key];
    public Conf.SoundInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
