
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Text.Json;


public partial class Tables
{
    public Conf.ItemInfos ItemInfos {get; }
    public Conf.AttributeInfos AttributeInfos {get; }
    public Conf.ModelInfos ModelInfos {get; }
    public Conf.HeroInfos HeroInfos {get; }
    public Conf.ColliderInfos ColliderInfos {get; }
    public Conf.SkillInfos SkillInfos {get; }
    public Conf.BuffInfos BuffInfos {get; }
    public Conf.PipelineInfos PipelineInfos {get; }
    public Conf.EffectInfos EffectInfos {get; }
    public Conf.EnemyInfos EnemyInfos {get; }
    public Conf.SoundInfos SoundInfos {get; }

    public Tables(System.Func<string, JsonElement> loader)
    {
        ItemInfos = new Conf.ItemInfos(loader("Conf.ItemInfo"));
        AttributeInfos = new Conf.AttributeInfos(loader("Conf.AttributeInfo"));
        ModelInfos = new Conf.ModelInfos(loader("Conf.ModelInfo"));
        HeroInfos = new Conf.HeroInfos(loader("Conf.HeroInfo"));
        ColliderInfos = new Conf.ColliderInfos(loader("Conf.ColliderInfo"));
        SkillInfos = new Conf.SkillInfos(loader("Conf.SkillInfo"));
        BuffInfos = new Conf.BuffInfos(loader("Conf.BuffInfo"));
        PipelineInfos = new Conf.PipelineInfos(loader("Conf.PipelineInfo"));
        EffectInfos = new Conf.EffectInfos(loader("Conf.EffectInfo"));
        EnemyInfos = new Conf.EnemyInfos(loader("Conf.EnemyInfo"));
        SoundInfos = new Conf.SoundInfos(loader("Conf.SoundInfo"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        ItemInfos.ResolveRef(this);
        AttributeInfos.ResolveRef(this);
        ModelInfos.ResolveRef(this);
        HeroInfos.ResolveRef(this);
        ColliderInfos.ResolveRef(this);
        SkillInfos.ResolveRef(this);
        BuffInfos.ResolveRef(this);
        PipelineInfos.ResolveRef(this);
        EffectInfos.ResolveRef(this);
        EnemyInfos.ResolveRef(this);
        SoundInfos.ResolveRef(this);
    }
}


